### ISSUE TITLE
DAG seems to be missing

### ISSUE THREAD

**Issue by JavierLTPromofarma** [habibdhif/docker-compose-airflow#1]
Hello, I have modified your docker-compose.yaml for using the LocalExecutor instead of Celery but the dags are missing. Could you help me, please?

![Captura de pantalla 2020-05-20 a las 15 22 36](https://user-images.githubusercontent.com/62240502/82451051-c39baa80-9aad-11ea-8f22-21d08dee3f59.png)

The Makefile is exactly the same as yours and my modified docker-compose.yaml is the following (I have also added an import of variables):
```
version: "3.7"
x-airflow-environment: &airflow-environment
  AIRFLOW__CORE__EXECUTOR: LocalExecutor
  AIRFLOW__CORE__LOAD_EXAMPLES: "False"
  AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow

services:
  postgres:
    image: postgres:11.5
    environment:
      POSTGRES_USER: airflow
      POSTGRES_DB: airflow
      POSTGRES_PASSWORD: airflow
  init:
    image: apache/airflow:1.10.10
    environment:
      <<: *airflow-environment
    depends_on:
      - postgres
    volumes:
      - ./dags:/opt/airflow/dags
      - ./plugins:/opt/airflow/plugins
      - ./variables_secret.json:/opt/airflow/variables_secret.json
    entrypoint: /bin/bash
    command: >
      -c "airflow list_users || (airflow initdb
      && airflow create_user --role Admin --username airflow --password airflow -e airflow@airflow.com -f airflow -l airflow
      && airflow variables -i /opt/airflow/variables_secret.json)"
    restart: on-failure
  webserver:
    image: apache/airflow:1.10.10
    ports:
      - 8080:8080
    environment:
      <<: *airflow-environment
    depends_on:
      - init
    volumes:
      - ./dags:/opt/airflow/dags
      - ./plugins:/opt/airflow/plugins
      - ./variables_secret.json:/opt/airflow/variables_secret.json
    entrypoint: /bin/bash
    command: -c "airflow variables -i /opt/airflow/variables_secret.json && airflow webserver"
    restart: always
  scheduler:
    image: apache/airflow:1.10.10
    environment:
      <<: *airflow-environment
    depends_on:
      - webserver
    volumes:
      - ./dags:/opt/airflow/dags
      - ./plugins:/opt/airflow/plugins
      - ./variables_secret.json:/opt/airflow/variables_secret.json
    entrypoint: /bin/bash
    command: -c "airflow variables -i /opt/airflow/variables_secret.json && airflow scheduler"
    restart: always
```
I hope you can help me. Thank you very much in advance
